### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by Lichapa**
In this project, we have developed a responsive website that changes view at different sizes below:

1. max-width-690px: Items are displayed in a vertical line and have a width of 100% to fill the screen.
2. Max-width-1024px: Items are aligned in rows but to a maximum of 3 items on each row. larger section only accomodating 2 items.
3. Wider than 1024px: Items are placed in rows depending on the width of the screen. We have used frex wrap to allow content to shift and fit on the screen depending on the width.

We have used flex, grid and block to position the elements.

### CODE REVIEW

**Review by kevcap — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUIRED♻️

  
#### Hey team, Is a pleasure to review such a good project! Congrats for the amazing work you guys already did, the project looks really nice and I can see that you guys are working hard on it, and we're almost done, there are just some minor changes that you guys have to implement to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] In medium and small screens the TNW logo should be at the navbar.
image
- [x] Your page have some overflow in some sections, please get rid of it.
image
- Small screen issues
- [ ] Your page is facing some horizontal overflow which is causing that horizontal bar
- [x] Add more margin-top to that first image so users can see it better.
image
- [x] Just as the medium screens, your page have text overflow at some sections, please fix i.
- [x] Add some margin-left in your page (those list points shouldn't be so close to the left border)
image
- [x] Add spacing between all these footer elements (icons and text)
image
When we scroll down, your navbar isn't fixed properly ⤵
[Image from Gyazo](https://gyazo.com/e156bf85b9f1fd20dd6476224b6eafb3)

## [OPTIONAL CHANGES]
- [ ] Add css and img folder inside a assets folder.

## Summary
✨ **Awesome job implementing that counter! 🥇**
✨ Overall your page looks really nice, congrats! 👌
✨ Good job with that project, it looks really good for a first review 💥
✨ Awesome CSS practices, congrats 😎
✨ You have a good understanding of semantic HTML! 🤓


## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> gmail</a> [Twitter Follow](https://twitter.com/intent/follow?screen_name=kevinnnmn) [](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @happiguru AND @umairarshadbutt 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [x] There are extra padding and spacing in the navbar from 691px to 1024px, so please manage to pass and spaces to make sure its responsiveness

|[Source Page](https://thenextweb.com/)|[Clone Page](https://rayan84.github.io/The-Next-Web-Clone/)|
|:---:|:---:|
|TNW-Original-navbar|Clone-TNW-navbar|

- [x] There is still an issue in the footer, as previous TSE explained [these screenshots at 350px]

|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/berhanu-tarekegn/the-next-web-clone/develop/index.html)|
|:---:|:---:|
|footer-orginal|footer-clone|

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://rayan84.github.io/The-Next-Web-Clone/) shows a good understanding and usage of Bootstrap. :100:
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Lichapa and @Rayan84! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
